### ISSUE TITLE
Example usage please ...

### ISSUE THREAD

**Issue by grekpg** [ccozkan/selenium-instagram-uploader#7]
```
python3 selenium-instagram-uploader.py 
Traceback (most recent call last):
  File "/home/grek/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "selenium-instagram-uploader.py", line 11, in <module>
    driver = webdriver.Firefox(profile)
  File "/home/grek/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/grek/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
```

**Comment by grekpg** [comment]
ok i add 

driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), firefox_profile=profile)

and work
